#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias bower='noglob bower'
alias cl='clear'
alias md='mkdir'
alias sp="source /etc/profile; source ${ZDOTDIR:-$HOME}/.zshenv; source ${ZDOTDIR:-$HOME}/.zprofile; source ${ZDOTDIR:-$HOME}/.zshrc; source ${ZDOTDIR:-$HOME}/.zlogin"
alias suu='sudo -s'
alias v='vim'
alias vv='sudo vim'

source /Users/gabe/.iterm2_shell_integration.zsh
